chat/urls.py
from django.conf.urls import patterns, url

from .views import ChatRoom, CreateMessage
from chat.views import CreateRoom
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',
    url(r'^$', login_required(CreateRoom.as_view()), name='lobby'),
    url(r'^(?P<room>.+)/msg/$', login_required(CreateMessage.as_view()), name='create_message'),
    url(r'^(?P<room>.+)/$', login_required(ChatRoom.as_view()), name='chatroom'),
)

project/urls.py
from django.conf.urls import patterns, include, url

import chat.urls

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'project.views.home', name='home'),
    # url(r'^project/', include('project.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
    url(r'', include(chat.urls)),
    
)

chat/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse_lazy

# Create your models here.
class Room(models.Model):
    name = models.CharField(max_length=64, unique=True)
    creator = models.ForeignKey(User)

    created = models.DateTimeField(auto_now_add=True)
    
    def get_absolute_url(self):
        return reverse_lazy('chatroom', kwargs={'room':self.name})
    
class Message(models.Model):
    room = models.ForeignKey(Room)
    user = models.ForeignKey(User)
    
    content = models.CharField(max_length=256) #somewhat arbitrary
    
    created = models.DateTimeField(auto_now_add=True)
    
    @staticmethod
    def get_for_room(room):
        """
        Helper for building a QS for messages in a room.
        """
        return Message.objects.filter(room=room)
    
    class Meta:
        ordering = ['-created'] 
    

chat/views.py
from django.views.generic import ListView
from django.views.generic.edit import CreateView
from django import forms
from .models import Message, Room
from django.shortcuts import get_object_or_404
from django.http.response import HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.core.serializers import serialize
from django.conf import settings

class ChatForm(forms.ModelForm):
    content = forms.CharField(max_length=256, label='',
                              widget=forms.TextInput(attrs={'size':100}))
    
    class Meta:
        model = Message
        exclude = ('user', 'room') #both provided by request and url, respectively

class RoomForm(forms.ModelForm):
    class Meta:
        model = Room
        exclude = ('creator')

class CreateRoom(CreateView):
    model = Room
    form_class = RoomForm

    def form_valid(self, form):
        """
        A message is POSTed to this view, but the user comes from 
        the Auth middleware and the room comes from the url.
        """
        form.instance.creator = self.request.user
        return super(CreateRoom, self).form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = CreateView.get_context_data(self, **kwargs)
        context['object_list'] = Room.objects.order_by('-created')
        return context
    
class ChatRoom(ListView):
    """
    Interface to the chat room.  Handles the initial room setup,
    posts of new messages, and retrieval of new messages.
    """
    model = Message
    form_class = ChatForm
    
    def get_queryset(self):
        """
        Override the default queryset to support two operations:
        - get the last X messages from this room
        - get the last messages from the room newer than Y
        """
        limit = getattr(settings, 'CHAT_HISTORY_LIMIT', 100)
        
        room = get_object_or_404(Room, name=self.kwargs.get('room'))
        qs = Message.get_for_room(room)

        since = int(self.request.GET.get('since', 0))
        if since:
            qs = qs.filter(pk__gt=since) #relying on primary keys being in order.
        qs = qs[0:limit] #if somebody has lagged more than 100 messages, there's a problem we can't fix
        return qs
    
    def get_context_data(self, **kwargs):
        context = ListView.get_context_data(self, **kwargs)
        context['object_list'] = context['object_list'][::-1] #reverse these at the last minute
        context['room'] = get_object_or_404(Room, name=self.kwargs.get('room'))
        context['form'] = ChatForm()
        context['poll_delay'] = getattr(settings, 'CHAT_REFRESH_RATE', 2)
        return context

    def get_template_names(self):
        template_names = ListView.get_template_names(self)
        if self.request.is_ajax():
            template_names = [f.replace('_list', '_list_ajax') for f in template_names]
        return template_names
    
class CreateMessage(CreateView):
    form_class = ChatForm
    model = Message

    def form_valid(self, form):
        """
        A message is POSTed to this view, but the user comes from 
        the Auth middleware and the room comes from the url.
        """
        form.instance.user = self.request.user
        form.instance.room = Room.objects.get(name=self.kwargs['room'])
        return super(CreateMessage, self).form_valid(form)

    def get_success_url(self):
        """
        Return to the room's url.
        """
        room = Room.objects.get(name=self.kwargs['room'])
        return room.get_absolute_url()

    def get(self, *args, **kwargs):
        """
        Should never get here, but if somebody loads this url, redirect to chat room.
        """
        return HttpResponseRedirect(self.get_success_url())


    def post(self, request, *args, **kwargs):
        content = request.POST.get('content')
        if not content:
            return HttpResponseRedirect(self.get_success_url())
        else:
            return super(CreateMessage, self).post(request, *args, **kwargs)
        

chat/templates/chat/base.html
<!DOCTYPE html>
<html lang="en">
<head>
   <title>{% block title %}The Demo Chat Site{% endblock %}</title>
</head>
<body>
<!-- BEGIN MAIN BODY -->
<div class="container wide">
    {% block content %}{% endblock %}
</div> 
<!-- END MAIN BODY -->

<script type="text/javascript" src="http://code.jquery.com/jquery-1.9.1.min.js"></script>

{% block script %}{% endblock %}    
<!--  begin common footer (to allow logging out -->
        {% if request.user.is_authenticated %}
          Hello, {{request.user}}. <a href='{% url 'logout' %}'>Logout</a>
        {% endif %}
<!-- end common footer -->

</body>
</html>

chat/templates/chat/message.html
<li class='message' id="chat_message_{{obj.pk}}" data-id='{{obj.pk}}'>{{obj.user.username}} at {{obj.created}}: {{obj.content}}</li>

chat/templates/chat/message_list.html
{% extends 'chat/base.html' %}
{% block content %}
<div id='header'>
<h1>{{room.name}}</h1>
</div>
<ul id="chatlog">
{% for obj in object_list %}
	{% include 'chat/message.html' %}
{% endfor %}
</ul>

<div id='footer'>
<form action="{% url 'create_message' room=room.name %}" method="post" id='create_message'>
{% csrf_token %}
{{form}}
<input type='submit' value='CHAT'>
</form>
{% endblock %}
</div>
{% block script %}
<script type='text/javascript'>
/**
 * This script handles live-updating of the chat log.
 * The approach is fairly dumb, merely asking the server for
 * new messages every 5 seconds and adding them to the chatlog as needed.
 * 
 * There's an extremely slim chance that if many people enter messages simultaneously
 * and the db is clever (or not clever?) about primary keys,
 * messages could appear out of order and/or get lost according to some users' perspectives.
 * On sqlite this is probably impossible since it's single-user-at-a-time.
 *
 * @todo: Refactor this into a separate file (also for minification).
 */


/**
 * Takes the results of an ajax request and appends it to the chatlog.
 */
var parse_response = function(what){
	what = jQuery.trim(what);
	if(what.length){
		$('#chatlog').append(what);
	}
}

/**
 * Figures out the the last message, builds an ajax request
 * and fires it off.
 */
var update_chat = function(){
	setTimeout(update_chat, {{poll_delay}}*1000); // do this first so any errors don't prevent it from happening.
	var last_message = $('#chatlog > .message').last();
	var id = last_message.data('id'); // get the id of the last message to use in the request
	var url = "{% url 'chatroom' room=room.name %}";
	$.ajax(url, {data: {since:id}}).done(parse_response);
}

/**
 * Handle clearing the chat input form.
 */
var clear_form = function(){
	$('#create_message').each(function(){this.reset();});
}

/**
 * Handle posting new messages via ajax.
 */
var post_message = function(event){
	event.preventDefault();
	var form = $(this);

	$.ajax({url : form.attr('action'),
			type : form.attr('method'),
			data : form.serialize()
		});
	clear_form();
}

/**
 * Bind event handlers for the poller and for the chat message submit.
 */
 $(document).ready( update_chat );
 $('#create_message').submit( post_message );
 


/**
 * Also, focus on the chat input box on page load.
 */
 $(document).ready(function(){
	 $('#id_content').focus();
 });
 
</script>
{% endblock %}

chat/templates/chat/message_list_ajax.html
{%comment%} Similar to message_list.html, but just the fragments of html for chat messages. {% endcomment %}
{% for obj in object_list %}
	{% include 'chat/message.html' %}
{% endfor %}

chat/templates/chat/room_form.html
{% extends 'chat/base.html' %}
{% block content %}
<div>
<h1>Create a new chat room</h1>
<form method='POST'>
{% csrf_token %}
{{ form }}
<input type='submit'>
</form>
</div>

<div>
<h1>Join an existing chat room</h1>
<ul>
{% for obj in object_list %}
<li><a href='{{obj.get_absolute_url}}'>{{obj.name}}</a> (created by {{obj.creator.username}})</li>
{% endfor %}
</ul>
</div>
{% endblock %}